name: draw_page
description: Simple drawing page
version: 0.0.2
author: tedomakharadze95@gmail.com
homepage: https://github.com/tedcrimson/packages/tree/master/draw_page/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
